# Generated by Django 4.0.6 on 2022-07-28 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0002_newsletter'),
    ]

    operations = [
        migrations.CreateModel(
            name='pricing_class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(blank=True, max_length=254, null=True)),
                ('price', models.CharField(blank=True, max_length=254, null=True)),
                ('period', models.CharField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
